version: '3.5' # We use version 3.5 syntax
services: # Here we define our service(s)
    app: # The name of the service
      image: birds-and-reels
      container_name: birds-and-reels-app # Container name
      build: . # Location of our Dockerfile
      volumes: # Volume binding
        - '.:/app'
      ports:
        - '4200:4200' # Port mapping
      command: >
        bash -c "ng serve --host 0.0.0.0 --port 4200"
